---

groups_to_create: 
  - name: developer
  - name: futurxadmin

admin_user:
  - username: sanjara
    ssh_keys: 
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrg+oEyQOb9UXij76JLtVpOTbYtKZsUaFSODlO7BFATLRtMeYIekrhWd+RFvOzz62dXsBlT1CZom1P+9ktgMV+lbriX9XaCOlMWeLhk+dG+yf7kumBSGgrw3gw7x7PpWrbm8LnRsPwiG/96POu/nJ/cu2CYDvsFdAAWlX182Lvm28NvSeDzOaNPCTM4GoLcOnqSnLYNBSqb9yyUxgA5L+5igDRsKn246U2VaYG1OpVeh8vXoltY2c8EfqlUE2s4LzTwm7y63OHE6d43cRn+bA1br8Gp51GRnq6xymw9nOC6THyNP4SNWuBWwyhTpT624CHjZOVgqGEzKHn4foAzvWh sandeep@DESKTOP-2ND5V67"
  - username: mgadhiya
    ssh_keys: 
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjFJPFZ4A0bPlVUEcV9Ym3u8oLrg0xXu5r/CkcBO2ABEnQyYneIjprfW9e8HPB2mbMn743VMrZEII+zL9Mk+4TFa3zaiUuoNLHQclfxByt/TNOIQCrYmxcFFrocFuTQP/Qf9ynht2mHSIqy1YS1jSBxR+3AjcOlUUcCZeJ08AZ4m4HekEfOnZ83MdXSelpoTIPuM9cOcoC8fsyzH80XzJUGPn8sjOh3MY1xz+CNTpiA5qDVUMnWRdTQTxrOVzvg6YZMbKdB6umXF36wtaaUQT+A7FpqAY7muHibntANJ0rpIHKdyUv/saYfaaM//qzEj36yRoIfTKisxU/uYKp+uNZ meetg@DESKTOP-JO1KDLE"
      
developer_user:
  - username: kshah
    ssh_keys: 
      - "ssh-rsa AAAAB3NzaC1yc2EAAAAD2fH41cRVTKLAlMlq9717ugSr20xHDwB6kTNoIxvEtUBPqNIwgubKCV2BnJwsqWhUeWpJza+4N0NQeQlBYggG0AYhXvPRfme9cJagzW3V4xIq70wEtV9uI8nCYeFzsyRFm53lyaiPYhZ+19ZbBWPv4zlOBtINdLEFGxQwCjOsmA4bL2cuVuJ/RTwFz1ATydX0hWTcpLeWNDp451/JnTNWBFONQurSwTZdZFsmxjuVzFrx9Xi7vcKtNZ2wgcp9yhlNbW+zJIACQdfU4zGWUvV0uzVkjunUct+PknV8nBd1GQaKLstAIJAAUQxg6tJj1lC9ofIw54vHVvpCYhHZOcfL SRKay CG@DESKTOP-051BK8JKAVYESHSHAH"
  

delete_user:
  - username: kshah
  


      


