---

- name: Creating groups
  group: name="{{item.name}}" gid="{{item.gid | default(omit)}}"
  with_items: "{{groups_to_create}}"
  tags: Creating_groups

- name: Per-user group creation
  group: name="{{item.username}}"
         gid="{{item.gid | default(item.uid) | default(omit)}}"
  with_items: 
    - "{{admin_user}}"
    - "{{developer_user}} "
  when: "'group' not in item and users_create_per_user_group"
  tags: per_user_group_creation

- name: User creation for admin
  user:
    name: "{{item.username}}"
    group: ''
    groups: futurxadmin
    shell: "{{item.shell if item.shell is defined else '/bin/bash'}}"
    home: "/home/{{item.username}}"
  with_items: "{{admin_user}}"
  tags: User_creation_for_admin

- name: User creation for developer
  user:
    name: "{{item.username}}"
    group: ''
    groups: developer
    shell: "{{item.shell if item.shell is defined else '/bin/bash'}}"
    home: "/home/{{item.username}}"
  with_items: "{{developer_user}}"
  tags: User_creation_for_developer

- name: SSH keys for admin user
  authorized_key:
    user: "{{item.0.username}}"
    key: "{{item.1}}"
    path: "{{ item.0.home | default('/home/' + item.0.username) }}/.ssh/authorized_keys"
  with_subelements:
    - "{{admin_user}}"
    - ssh_keys
    - skip_missing: yes
  tags: SSH_keys_for_admin_user


- name: SSH keys for dev user
  authorized_key:
    user: "{{item.0.username}}"
    key: "{{item.1}}"
    path: "{{ item.0.home | default('/home/' + item.0.username) }}/.ssh/authorized_keys"
  with_subelements:
    - "{{developer_user}}"
    - ssh_keys
    - skip_missing: yes
  tags: SSH_keys_for_dev_user



- name: Deleted user removal
  user:
    name: "{{item.username}}"
    state: absent
    remove: "{{item.remove | default(omit)}}"
    force: "{{item.force | default(omit)}}"
  with_items: "{{delete_user}}"
  tags: Deleted_user_removal



